APP = {
    "id": "assistant",
    "title": "Dieter Assistant",
    "nav_label": "Assistant",
    "home_url": "/apps/assistant/planner",
    "route_prefixes": ("/apps/assistant", "/apps/planner", "/dashboard"),
    "body_class": "planner-shell-page",
    "shell_class": "app-shell-planner",
    "top_class": "",
    "actions_class": "assistant-shell-actions",
    "chat_button_class": "app-shell-chat-button",
    "menu_class": "",
    "icon_class": "",
    "menu_summary": "Open Assistant navigation",
    "menu_label": "Assistant section navigation",
    "issue_area": "Assistant / Planner",
    "band_label": "Assistant utility navigation",
    "subtitle": "Plan projects, remember agenda items, and keep life moving.",
    "home_label": "Assistant Home",
    "nav_items": (
        {"label": "Planner", "url": "/apps/assistant/planner"},
        {"label": "Scheduler", "url": "/apps/assistant/scheduler"},
    ),
    "theme": {
        "header": "#083344",
        "color": "#164e63",
        "border": "#a5f3fc",
        "panel": "#ecfeff",
        "panel_strong": "#cffafe",
        "text": "#155e75",
        "hover": "#cffafe",
        "subtitle": "#cffafe",
    },
    "launcher_card": {
        "class": "planner-launch-card",
        "kicker": "Assistant",
        "title": "Dieter Assistant",
        "url": "/apps/assistant/planner",
        "description": "Planner, Scheduler, priorities, blockers, and task steps.",
    },
}
