APP = {
    "id": "kitchen",
    "title": "Dieter Kitchen",
    "nav_label": "Kitchen",
    "home_url": "/apps/recipes",
    "route_prefixes": ("/apps/recipes",),
    "body_class": "recipe-shell-page",
    "shell_class": "app-shell-recipe recipe-app-heading",
    "top_class": "recipe-app-heading-inner",
    "actions_class": "recipe-app-actions",
    "chat_button_class": "kitchen-chat-button",
    "menu_class": "recipe-app-menu",
    "icon_class": "recipe-app-menu-icon",
    "menu_summary": "Open Kitchen navigation",
    "menu_label": "Recipe app navigation",
    "issue_area": "Kitchen / Recipes",
    "band_label": "Kitchen utility navigation",
    "subtitle": "Plan meals, build grocery lists, and interactive recipes",
    "home_label": "Kitchen Home",
    "nav_items": (
        {"label": "Meal Plan", "url": "/apps/recipes"},
        {"label": "Past Grocery Lists", "url": "/apps/recipes/grocery-lists"},
        {"label": "Create New Meal", "url": "/apps/recipes/create-meal"},
        {"label": "Manage", "url": "/apps/recipes/manage"},
        {"label": "Import Recipes", "recipe_import_url": True},
    ),
    "theme": {
        "header": "#2e064f",
        "color": "#3b0764",
        "border": "#decdf8",
        "panel": "#fbf7ff",
        "panel_strong": "#f1e9ff",
        "text": "#4c1d95",
        "hover": "#f1e9ff",
        "subtitle": "#ddd6fe",
    },
    "launcher_card": {
        "class": "kitchen-launch-card",
        "kicker": "Kitchen",
        "title": "Dieter Kitchen",
        "url": "/apps/recipes",
        "description": "Meal plans, grocery lists, recipe cards, and cooking feedback.",
    },
}
