APP = {
    "id": "issues",
    "title": "Dieter Studio",
    "nav_label": "Studio",
    "home_url": "/apps/issues",
    "route_prefixes": ("/apps/issues",),
    "body_class": "issues-shell-page",
    "shell_class": "app-shell-issues",
    "top_class": "",
    "actions_class": "",
    "chat_button_class": "",
    "menu_class": "recipe-app-menu",
    "icon_class": "recipe-app-menu-icon",
    "menu_summary": "Open Studio navigation",
    "menu_label": "Studio app navigation",
    "issue_area": "",
    "show_issue_item": False,
    "show_chat_button": False,
    "band_label": "Studio utility navigation",
    "subtitle": "Turn app feedback into scoped plans, Codex runs, and tested improvements.",
    "home_label": "Studio Home",
    "nav_items": (
        {"label": "Studio", "url": "/apps/issues"},
    ),
    "theme": {
        "header": "#881337",
        "color": "#be123c",
        "border": "#fecdd3",
        "panel": "#fff1f2",
        "panel_strong": "#ffe4e6",
        "text": "#9f1239",
        "hover": "#ffe4e6",
        "subtitle": "#fecdd3",
    },
    "launcher_card": {
        "class": "issues-launch-card",
        "kicker": "Studio",
        "title": "Dieter Studio",
        "url": "/apps/issues",
        "description": "Review feedback, synthesize plans, approve Codex runs, and track implementation.",
    },
}
