APP = {
    "id": "music",
    "title": "Dieter Music",
    "nav_label": "Music",
    "home_url": "/apps/music/playlists",
    "route_prefixes": ("/apps/music/playlists", "/apps/playlists"),
    "body_class": "playlists-shell-page",
    "shell_class": "app-shell-playlists playlists-app-heading",
    "top_class": "playlists-app-heading-inner",
    "actions_class": "playlists-app-actions",
    "chat_button_class": "playlists-chat-button",
    "menu_class": "playlists-app-menu",
    "icon_class": "playlists-app-menu-icon",
    "menu_summary": "Open Playlist navigation",
    "menu_label": "Music app navigation",
    "issue_area": "Music",
    "band_label": "Playlist utility navigation",
    "subtitle": 'Say "make a playlist..." for songs, then edit matches before sending them to Spotify.',
    "home_label": "Music Home",
    "nav_items": (
        {"label": "Music", "url": "/apps/music/playlists"},
    ),
    "theme": {
        "header": "#7c2d12",
        "color": "#c2410c",
        "border": "#fed7aa",
        "panel": "#fff7ed",
        "panel_strong": "#ffedd5",
        "text": "#9a3412",
        "hover": "#ffedd5",
        "subtitle": "#fed7aa",
    },
    "launcher_card": {
        "class": "playlists-launch-card",
        "kicker": "Music",
        "title": "Dieter Music",
        "url": "/apps/music/playlists",
        "description": "Dictate playlists, edit songs, and submit them to Spotify.",
    },
}
