APP = {
    "id": "launcher",
    "title": "Dieter",
    "nav_label": "Apps",
    "home_url": "/apps",
    "exact_paths": ("/", "/apps", "/admin/members"),
    "body_class": "launcher-shell-page",
    "shell_class": "app-shell-launcher",
    "top_class": "",
    "actions_class": "recipe-app-actions",
    "chat_button_class": "planner-chat-button",
    "menu_class": "recipe-app-menu",
    "icon_class": "recipe-app-menu-icon",
    "menu_summary": "Open Dieter navigation",
    "menu_label": "Dieter app navigation",
    "issue_area": "",
    "band_label": "Dieter navigation",
    "subtitle": "Open an app or ask Dieter to help from here.",
    "home_label": "Dieter Home",
    "nav_items": (
        {"label": "Apps", "url": "/apps"},
    ),
    "theme": {
        "header": "#0f172a",
        "color": "#334155",
        "border": "#cbd5e1",
        "panel": "#f1f5f9",
        "panel_strong": "#e2e8f0",
        "text": "#334155",
        "hover": "#e2e8f0",
        "subtitle": "#e2e8f0",
    },
}
