APP = {
    "id": "trainer",
    "title": "Dieter Trainer",
    "nav_label": "Trainer",
    "home_url": "/apps/trainer",
    "route_prefixes": ("/apps/trainer",),
    "body_class": "trainer-shell-page",
    "shell_class": "app-shell-trainer trainer-app-heading",
    "top_class": "trainer-app-heading-inner",
    "actions_class": "trainer-app-actions",
    "chat_button_class": "trainer-chat-button",
    "menu_class": "trainer-app-menu",
    "icon_class": "trainer-app-menu-icon",
    "menu_summary": "Open Trainer navigation",
    "menu_label": "Trainer section navigation",
    "issue_area": "Trainer",
    "band_label": "Trainer utility navigation",
    "subtitle": "Build workouts, schedule sessions, and track training history.",
    "home_label": "Trainer Home",
    "nav_items": (
        {"label": "Coach Dashboard", "url": "/apps/trainer/coach", "trainer_mode_is": "coach"},
        {"label": "Coaching", "url": "/apps/trainer/coaching", "trainer_mode_is": "athlete"},
        {"label": "Workouts", "url": "/apps/trainer/workouts"},
        {"label": "Upcoming", "url": "/apps/trainer/upcoming", "trainer_mode_not": "coach"},
        {"label": "Past", "url": "/apps/trainer/past", "trainer_mode_not": "coach"},
        {"label": "Strava Imports", "url": "/apps/trainer/imports", "trainer_mode_not": "coach"},
        {"label": "Settings", "url": "/apps/trainer/settings"},
    ),
    "theme": {
        "header": "#022c22",
        "color": "#065f46",
        "border": "#a7f3d0",
        "panel": "#ecfdf5",
        "panel_strong": "#d1fae5",
        "text": "#047857",
        "hover": "#d1fae5",
        "subtitle": "#bbf7d0",
    },
    "launcher_card": {
        "class": "trainer-launch-card",
        "kicker": "Training",
        "title": "Dieter Trainer",
        "url": "/apps/trainer",
        "description": "Run, bike, strength, upcoming sessions, and workout history.",
    },
}
